### ISSUE TITLE
Readme intro video has been archived

### ISSUE THREAD

**Issue by seabbs** [ProvTools/Rclean#91]
This package looks really neat - good job. 

I noticed that the intro video is no longer available - looks like it has been archived.

Sam

**Comment by MKLau** [comment]
Thanks, Sam. 

Thanks for reviewing and catching this. 

I’ll re-make that demo and update the link.

**Comment by seabbs** [comment]
Awesome

**Comment by MKLau** [comment]
asciinema.org just de-archived and permalinked the video. Good to go!
